# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
#  - osx
julia:
  - 1.1
env:
  - GROUP=Interface
  - GROUP=Interface2
  - GROUP=Interface3
  - GROUP=AlgConvergence
  - GROUP=AlgConvergence2
  - GROUP=AlgConvergence3
#matrix:
#  allow_failures:
#    - julia: nightly
notifications:
  email: false
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("StochasticDiffEq"); Pkg.test("StochasticDiffEq"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("StochasticDiffEq")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("StochasticDiffEq")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
